name: spa_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable_text: ^2.3.0 # shows expand option when when exceeds the specified limit
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # date/time
  flutter_svg: ^1.0.3  # svg icon
  provider: ^6.0.2 # state management 
  http: ^0.13.4 # make http request to the server
  shared_preferences: ^2.0.13 # save data locally
  cached_network_image: ^3.2.0 # store image as cache
  image_picker: ^0.8.5+3 # image selector
  image_cropper: ^2.0.2 # image cropper
  pinch_zoom_image_last: ^0.4.1 # pincg image to zoom
  http_parser: ^4.0.1 # convert data type for uploading multipartfile like image
  rxdart: ^0.27.4 # to allow multiple use of stream
  flutter_staggered_grid_view: ^0.6.2 # display images in staggered view
  scrollable_positioned_list: ^0.3.2 # for scrolling to index/item in listview
  firebase_core: ^2.14.0 # for using firebase services
  firebase_messaging: ^14.6.4 # for push notification
  flutter_local_notifications: ^9.9.1 # for push notification
  carousel_slider: ^4.1.1 # slide images
  smooth_page_indicator: ^1.0.0+2 # for dot indication while sliding images
  url_launcher: ^6.1.5 # for launching url 
  socket_io_client: ^1.0.2 # for chatting
  firebase_dynamic_links: ^5.3.3 # navigating to shared post 
  share_plus: ^4.0.10+1 # for sharing post
  badges: ^2.0.3 # for notification badge
  connectivity_plus: ^2.3.9 # checks internet connection in the app
  package_info_plus: ^3.0.1 # get app info
  webview_flutter: ^4.0.0 # to display e-commerce web view
  permission_handler: ^10.2.0 # permission request
  flutter_easyloading: ^3.0.5 # easy loading
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0 # for changing app icon

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/main_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/adaptive_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: HelveticaLight
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.ttf

    - family: HelveticaRegular
      fonts:
        - asset: assets/fonts/HelveticaNeueRegular.ttf

    - family: HelveticaMedium
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.ttf

